#!/usr/bin/env node
/**
 * Embeds config/, prompts/, and schemas/ into src/config/embeddedData.ts
 * so the loader can use them when the filesystem doesn't have them (e.g. Trigger.dev deploy).
 * Run before build: node scripts/embed-config.mjs
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const CONFIG_NAMES = [
  "categories.json",
  "subcategories.json",
  "actions.json",
  "routing_thresholds.json",
  "gmail_labels.json",
  "rules.json",
  "archive_labels.json",
];
const PROMPT_NAMES = ["summarizer.md", "category_router.md", "subcategory_router.md", "label_router.md"];
const SCHEMA_NAMES = [
  "categories.json",
  "subcategories.json",
  "actions.json",
  "routing_thresholds.json",
  "gmail_labels.json",
  "rules.json",
  "archive_labels.json",
];

const configDir = join(ROOT, "config");
const promptDir = join(ROOT, "prompts");
const schemaDir = join(ROOT, "schemas");

const configFiles = {};
for (const name of CONFIG_NAMES) {
  const p = join(configDir, name);
  if (existsSync(p)) configFiles[name] = JSON.parse(readFileSync(p, "utf-8"));
}

const promptFiles = {};
for (const name of PROMPT_NAMES) {
  const p = join(promptDir, name);
  if (existsSync(p)) promptFiles[name] = readFileSync(p, "utf-8");
}

const schemaFiles = {};
for (const name of SCHEMA_NAMES) {
  const p = join(schemaDir, name);
  if (existsSync(p)) schemaFiles[name] = JSON.parse(readFileSync(p, "utf-8"));
}

const out = `/** Auto-generated by scripts/embed-config.mjs - do not edit manually */\n
export const embeddedConfigFiles: Record<string, unknown> = ${JSON.stringify(configFiles, null, 2)} as Record<string, unknown>;
export const embeddedPromptFiles: Record<string, string> = ${JSON.stringify(promptFiles, null, 2)} as Record<string, string>;
export const embeddedSchemaFiles: Record<string, object> = ${JSON.stringify(schemaFiles, null, 2)} as Record<string, object>;
`;

const outPath = join(ROOT, "src", "config", "embeddedData.ts");
writeFileSync(outPath, out, "utf-8");
console.log("Wrote", outPath);
